spring.application.name=ProjectModule
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/scaler
spring.datasource.username=creddy
spring.datasource.password=creddyuser
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
